[DRAFT] common: IRCv3++, more IRCv3, allow disabling IRCv3 caps
quassel/quassel pull request #545
Opened 2020-07-21 02:27 UTC by digitalcircuit

## IRCv3 stuff!
* Bundle in [the PostgreSQL column changes PR](https://github.com/quassel/quassel/pull/478 )
* Bundle in changes [from justJanne's IRCv3 PR](https://github.com/quassel/quassel/pull/479 ) with new fixes/polish
* Add more IRCv3 capabilities!
* Allow disabling IRCv3 capabilities!
* Clean up the feature supported icons from `dialog-*` to `emblem-*`; looks nicer on Breeze

## Things not yet done
- [ ] Write up a good description
- [ ] Screenshots and examples
- [ ] Testing

2020-07-22 04:02 UTC, digitalcircuit commented
I'll be removing `echo-message` from the default capability negotiation so it can only be enabled through a manual `/CAP REQ echo-message`, and moving it into an independent commit for easier revert if need be.

I'll also clean up the `Features` UI to remove `echo-message`.  I might split out the UI additions for `server-time` into a separate commit as well just for easier reference later (versus all the code that went into adding `skipCaps` editing support).

2020-09-03 05:40 UTC, digitalcircuit commented
This is ready for review!

2020-10-04 19:07 UTC, digitalcircuit commented
Force-pushed to rebase after recent merges, fixing merge conflicts with `quassel.h`.  No functional changes.

2020-10-13 20:16 UTC, Sput42 requested changes

2020-10-13 20:16 UTC, Sput42 commented on src/core/eventstringifier.cpp
> +void EventStringifier::defaultHandler(const QString& ctcpCmd, CtcpEvent* e) {
Brace jumped up a line...

2020-10-13 20:16 UTC, Sput42 commented on src/core/eventstringifier.cpp
> +                       .arg(e->ctcpCmd(), nickFromMask(e->prefix()),e->param()));
Slightly weird and confusing line breaking and spacing here..

2020-10-13 20:43 UTC, digitalcircuit commented on src/core/corenetwork.cpp
> +        sortedCaps.sort();
Agreed!  And I think every place that Quassel itself writes to `NetworkInfo::skipCaps`, it sorts first.  However, if someone manually modifies the database or uses a third-party client that doesn't enforce sorting, the skipped caps may be unsorted which will break the following list intersection.

If that's a risk we're willing to take (and it might be unlikely), instead, I could enforce sorting when loading from the database and skip it here.

`caps()` comes from the network unsorted, and in Quassel 0.13 I had intentionally left it unsorted so Quassel could print caps in the order returned by the network (before sorting when negotiating), just in case the order of caps become important in distinguishing buggy/broken behavior.  It's not required though.

2020-10-13 20:45 UTC, digitalcircuit commented on src/core/corenetwork.cpp
> +        QStringList sortedCaps = QStringList(caps());
I think I had to create a copy of the `QStringList` in order to be able to modify/sort `caps()` (since it's a constant), and I may have been wanting to avoid modifying the original list for `networkInfo().skipCaps` since I hadn't checked if that'd have any protocol side-effects - the latter I can certainly toss out.

I'll test compiling this without the copy.  [See also the reply below](https://github.com/quassel/quassel/pull/545#discussion_r504246853).

2020-10-13 20:48 UTC, digitalcircuit commented on src/qtui/settingspages/networkssettingspage.cpp
> +        ui.enableCapsStatusLabel->setText(tr("Your Quassel core is too old to configure features"));
I've distinguished between "features" and "IRCv3 capabilities", since some features (e.g. showing messages as the server sent it to others) will require multiple capabilities (`echo-message`, `labeled-response`, etc).  And I'm not sure if we'd want to put things in this list which technically aren't part of IRCv3.

That said, it seems fine to just call this "IRCv3 features" to make it more distinguishable in e.g. support requests.  The `Details` button sorta explains the difference anyways.

2020-10-13 20:49 UTC, digitalcircuit commented on src/core/eventstringifier.cpp
> +                       .arg(e->ctcpCmd(), nickFromMask(e->prefix()),e->param()));
That's probably since I forgot to bump Qt Creator's shown line width from 100 columns or whatever it had been to the more recent wider width.  I'll just make the `tr("…").arg(…)` into one line.

2020-10-13 20:59 UTC, justjanne commented on src/core/SQL/PostgreSQL/setup_000_quasseluser.sql
> +       username varchar(8703) UNIQUE NOT NULL,
VARCHAR fields end up embedded in the row, while TEXT fields end up in an additional TOAST heap, causing slower lookup times due to an additional pointer chase

2020-10-17 04:20 UTC, digitalcircuit commented on src/core/SQL/PostgreSQL/setup_040_network.sql
> +       skipcaps text,                                       -- Space-separated IRCv3 caps to not auto-negotiate
Now I see what I did - I had copy-pasted from another instance of `text` in this file without stopping to see which was more correct.  Thanks for calling this out, will be fixed to `TEXT`!

2020-10-17 05:10 UTC, digitalcircuit commented on src/core/corenetwork.cpp
> +        QStringList sortedCaps = QStringList(caps());
Strange, it works now.  I suspect I got mixed up when making other changes and never went back to recheck this.  Thank you!

While I was here, I cleaned up the type to `auto sorted[…] = […]` as well.  This will be part of the next push.

2020-10-17 05:29 UTC, digitalcircuit commented on src/qtui/settingspages/networkssettingspage.cpp
> +        ui.enableCapsStatusLabel->setText(tr("Your Quassel core is too old to configure features"));
Fixed as requested in the upcoming push!  I'll update the PR screenshot, too.

For consistency, I also adjusted the message box that shows from clicking `Details…`:
```diff
- tr("Your Quassel core is too old to configure network features")
+ tr("Your Quassel core is too old to configure IRCv3 network features")
```

2020-10-17 05:45 UTC, digitalcircuit commented
I've addressed all comments except for…

* The [PostgreSQL `VARCHAR` vs `TEXT` discussion](https://github.com/quassel/quassel/pull/545#discussion_r504255028)
  * Awaiting reply; justJanne explained there is a performance impact
* The [matter of sorting capabilities during negotiation vs. protocol-level](https://github.com/quassel/quassel/pull/545#discussion_r504246853 )
  * Awaiting reply; I'm unsure of the best approach with handling third-party clients

Thank you for your feedback - this should be closer to the finish line :slightly_smiling_face:

2020-11-04 07:13 UTC, Sput42 commented on src/core/SQL/PostgreSQL/setup_000_quasseluser.sql
> +       username varchar(8703) UNIQUE NOT NULL,
@justjanne Did some research, seems like that is true for MySQL. The Postgres docs state that `VARCHAR(n)`, `VARCHAR` and `TEXT` are identical except for a size check when inserting into the former, but that there is otherwise no performance or storage difference. For sqlite it was hard to find information, but apparently they simply ignore the number and store `VARCHAR(n)` as `TEXT` anyway, although I found a single post claiming that the limit would be used for "query planning".

Given that my main worry was that we would be wasting space, which doesn't seem to be the case in any of the common db engines including MySQL, I don't care too much which way to go. I just found the 8703 char limit slightly obscure if you aren't familiar with IRCv3 specifications, and I wonder if we really should hardcode that (in other words, if the limit gives us any benefit).

2020-11-04 07:18 UTC, Sput42 commented on src/core/corenetwork.cpp
> +        sortedCaps.sort();
Would it make sense then to just sort once upon receipt, and remove all the other sorts? In that case, if order ever became important, we could care about that at the root, and would retain the order throughout the rest of the code. Arguably, we'd like to log them in the order received (or used/sorted if not imported) anyway...

2020-11-04 07:42 UTC, Sput42 commented
See my comments to the two open questions. I'll wait a bit for another round of feedback (or your decision which way to go in the end), then we can finally merge this - rest is fine, thx for fixing!

2020-11-07 01:00 UTC, digitalcircuit commented on src/core/corenetwork.cpp
> +        sortedCaps.sort();
### Sorting `skipCaps`
For `skipCaps`, I think that makes sense, and could look like this:

1.  Modify `void Network::setSkipCaps(const QStringList& skipCaps)` to sort first before applying/syncing
2.  Modify `QDataStream& operator>>(QDataStream& in, NetworkInfo& info)` to sort on deserialization
3.  Update comment in `void NetworkInfo::skipCapsFromString(const QString& flattenedSkipCaps)` to clarify reason for sorting
4.  Remove other sorting of `skipCaps`
5.  *Optional:* Add sorting to `QString NetworkInfo::skipCapsToString() const`
     * This ensures the `Advanced…` dialog under the Features tab on the Networks settings page always shows a sorted list (subjectively looks nicer, no functional impact), and ensures it's sorted when saving to the database (doesn't matter, will be sorted on load)

If I'm reading `NetworkInfo networkInfo() const;` correctly, this should prevent code from outside of the `Network` class from modifying `skipCaps` without it being sorted.

### Sorting `caps`
For `caps` which is filled from the network, I also agree, I think - that's why I'm sorting a copy here, instead of sorting the caps stored directly in the Network class.  Quassel later displays the network-offered caps in the order the network sent them (the `Ready to negotiate (found: %1)` message).

2020-11-08 03:02 UTC, digitalcircuit commented on src/core/corenetwork.cpp
> +        sortedCaps.sort();
I overcomplicated this as usual :upside_down_face: 

In hindsight, I can simply sort within `Network::setSkipCaps()` and adjust `CoreNetwork` to call `Network::skipCaps()` instead of reaching into `networkInfo().skipCaps` - the only other code in `CoreNetwork` that referenced `networkInfo()` like this was the `useSASL` check, which might've been an oversight - I'll fix that up in a new commit.

I'm adding sorting to `NetworkInfo::skipCapsToString()` as well just for display purposes for the `Advanced…` edit dialog, which also results in Quassel saving `skipCaps` sorted to the database, too.

2020-11-08 03:27 UTC, digitalcircuit commented on src/core/corenetwork.cpp
> +        sortedCaps.sort();
Test case:

`corenetwork.cpp`
```cpp
    if (!skipCaps().isEmpty() && !caps().isEmpty()) {
        // Find the entries that are common to skipCaps() and caps().  This represents any
        // capabilities supported by the server that were skipped.

        // Both skipCaps() and caps() are already lowercase
        // std::set_intersection requires sorted lists, and we can't modify the original lists.
        //
        // skipCaps() should already be sorted.  caps() is intentionally not sorted elsewhere so
        // Quassel can show the capabilities in the order transmitted by the network.
        auto sortedCaps = caps();
        sortedCaps.sort();

        showMessage(NetworkInternalMessage(
            Message::Server,
            BufferInfo::StatusBuffer,
            "",
            tr("DEBUG TEST - skipCaps(): %1").arg(skipCaps().join(", "))
        ));

        // Find the intersection between skipped caps and server-supplied caps
        std::set_intersection(skipCaps().cbegin(), skipCaps().cend(),
                              sortedCaps.cbegin(), sortedCaps.cend(),
                              std::back_inserter(capsSkipped));
    }
```

With this SQLite edit to intentionally set out-of-order `skipCaps`:
```sql
update network set skipcaps='extended-join away-notify' where networkname='Local (Bitlbee)';
```

Results in this in the server buffer:
```
* Requesting capability list...
[localhost] BitlBee-IRCd initialized, please go on
* DEBUG TEST - skipCaps(): away-notify, extended-join
* Ready to negotiate (found: sasl, userhost-in-names, multi-prefix, away-notify, extended-join, server-time)
* Quassel is configured to ignore some capabilities (skipped: away-notify, extended-join)
* Negotiating capabilities (requesting: sasl, multi-prefix, server-time, userhost-in-names)...
```

Success! :heavy_check_mark:  And editing capabilities with the Network's `Advanced…` dialog works, too.

2020-11-08 03:33 UTC, digitalcircuit commented
I've [addressed all comments as per the force-push view](https://github.com/quassel/quassel/compare/497432c094373113313f5a327b6c18ec1e012e2d..b5d72f816aa1b6fc095b3d73cde9306fc7406b62 ) except for…

* The [PostgreSQL `VARCHAR` vs `TEXT` discussion](https://github.com/quassel/quassel/pull/545#discussion_r504255028)
  * Awaiting reply; letting `@justJanne` respond first before making changes
  * Alternatively, I could make the change and wait for a comment…?

I've not thoroughly retested, but [after redoing `skipCaps` sorting](https://github.com/quassel/quassel/pull/545#discussion_r519249214 ) I've [done some fundamental checks](https://github.com/quassel/quassel/pull/545#discussion_r519250794).

I also added a minor cleanup in the form of this commit: [`core: In CoreNetwork, check Network::useSasl()`](https://github.com/quassel/quassel/pull/545/commits/54f47ec660850c8215e4ff62ad24a2e222e0deba).

2020-11-08 10:48 UTC, justjanne commented
@digitalcircuit as I was told yesterday (TIL), in more recent versions VARCHAR and TEXT are by default the same anyway. So it doesn't seem to matter, and if specific behaviour is needed, it can be achieved separately.

2020-11-08 21:10 UTC, digitalcircuit commented
I've [addressed all comments as per the force-push view](https://github.com/quassel/quassel/compare/b5d72f816aa1b6fc095b3d73cde9306fc7406b62..508613c041cd29358a954eca81a5f4cd36872689 ).  I amended [the PostgreSQL commit message accordingly](https://github.com/quassel/quassel/pull/545/commits/95f328ee8aee8a9e4b5e4ce5ff83eb06e8121358 ), too.

In this situation, I retested freshly setting up a Quassel core with a blank PostgreSQL database, then retested upgrading a Quassel core PostgreSQL database from 0.12.5 to this PR.  In both cases, it appeared successful, with messages correctly sending.

Thank you `Sput` for your review, `justJanne` for making sure assumptions were double-checked, and `jcolsen` for the initial PostgreSQL changes.  Hopefully, fingers crossed, everything is good to go!

2020-11-09 03:29 UTC, digitalcircuit commented on src/core/SQL/PostgreSQL/setup_000_quasseluser.sql
> +       username varchar(8703) UNIQUE NOT NULL,
With [the latest revision of commits](https://github.com/quassel/quassel/pull/545#issuecomment-723666347 ), I've addressed this by switching from `VARCHAR(n)` to `TEXT`.

2020-11-28 12:41 UTC, Sput42 approved these changes

2020-11-28 12:42 UTC, merged